package com.JDBC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class JDBC 
{
	public String getUserQuery(Gui temp) 
	{
	      temp.getUserInput();
	      Gui userQuery = temp;
	      System.out.println("userQuery");
	      return temp;
	}
	
	public static void main(String[] args) throws SQLException 
	{
		String url = "jdbc:mysql://localhost:3306/sculptures";
		String userName = "root";
		String password = "sqlroot4";
		String query = "select * from sculptures";
		Gui temp = getUserQuery(temp);
		String userQuery = temp;
		int columnNumber = 20; //number of rows in database
		
		//Make sure JConnector Driver is working
		try 
		{
			Class.forName("com.mysql.cj.jdbc.Driver");
		}
		catch (ClassNotFoundException e)
		{
			e.printStackTrace();
		}
		
		//Connection
		try
		{
			//go to driver
			Connection con = DriverManager.getConnection(url, userName, password);
			//Creates a Statement object for sending SQL statements to the database.
			Statement statement = con.createStatement();
			//A table of data representing a database result set, which is generated by the statement^ that queries the database.
			ResultSet result = statement.executeQuery(query);
			ResultSet result2 = statement.executeQuery(userQuery);
			
			//loop through data
			while (result.next()) 
			{
				String sculpturesData = "";
				for (int i=1; i<columnNumber; i++)
				{
					//get String of column (i)
					sculpturesData += result.getString(i) + " || ";
				}
				System.out.println(sculpturesData); //print each row
			}
			
			while (result2.next()) 
			{
				String sculpturesData = "";
				for (int i=1; i<columnNumber; i++)
				{
					//get String of column (i)
					sculpturesData += result2.getString(i) + " || ";
				}
				System.out.println(sculpturesData); //print each row
			}
		}
		catch (SQLException e)
		{
			e.printStackTrace();
		}
		
		
	}
	
}
